### PR TITLE
Travel request for OpenJS World Europe

### PR DESCRIPTION
**Pull request by JakobJingleheimer**
# Info

* Request for: Collab Summit and OSSEU 2023
* Dates: 17¹ – 21 September
* Travelling from: Amsterdam, Netherlands

¹ I'm actually arriving the Saturday, but that's just a holiday

# Expenses

```
€ 119 Flight (Amsterdam ↔︎ Bilbao)
€ 593 Hotel
€ 275 Registration
€ ~30 Transportation (public transit doesn't run early enough for the 1 flight to Bilbao)
━━━━
€1,020 Total
```

@openjs-foundation/cpc

### CODE REVIEW

**Review by ovflowd — APPROVED** [review]

**Comment by ovflowd** [comment]
cc @openjs-foundation/cpc

**Review by anonrig — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by JakobJingleheimer** [comment]
I just booked my flight. The one I had pinned earlier isn't available anymore; the new one is €168.

The other costs cited aside from transit are locked in.

**Comment by ovflowd** [comment]
The price change sounds reasonable enough and within margin.

**Pull request merged**
