### PR TITLE
Travel request for OpenJS World China - Kazuhito Yokoi

### PR DESCRIPTION
**Pull request by kazuhitoyokoi**
# Info
- Request for: OpenJS World China / Open Source Summit China 2023 
- Dates: September 26th - September 28th 
- Traveling from: Tokyo, Japan

# Estimated Expenses
- Flight: 1,091 USD (156,840 YEN, Tokyo->Shanghai: JL81,  Shanghai->Tokyo: JL86)
- Hotel: 712 USD (5,130.40 CNY, [hotel recommended by OSS China](https://www.lfasiallc.com/kubecon-cloudnativecon-open-source-summit-china/venue-travel/#hotel-information))
- Total: 1,803 USD

@openjs-foundation/cpc

### CODE REVIEW

**Comment by kazuhitoyokoi** [comment]
Hello everyone. I'm a contributor to the Node-RED project.
My recent activities are as follows.

- [A Node-RED contributor](https://github.com/node-red/node-red/graphs/contributors) for 7 years 
- One of the organizers in the [Node-RED conference](https://nrcon.nodered.org/) 
- Speker at OpenJS World 2023, 2021, and Node+JS Interactive 2018
(I hope that some people remember me at OpenJS World 2023.)

I heard that Nick O'Leary, creator of Node-RED, introduced me to the OpenJS Program Committee as a speaker at OpenJS World China / Open Source Summit China. So I was invited by Robin and the OpenJS Program Committee.

I'm really glad to have this great opportunity and would like to talk about Node-RED and community.

**Review by ovflowd — APPROVED** [review]
Approved :)

And we do (or at least I do) remember you!

**Comment by ovflowd** [comment]
cc @openjs-foundation/cpc as he's a speaker at one of our Events.

**Review by anonrig — APPROVED** [review]

**Review by VoltrexKeyva — APPROVED** [review]

**Comment by kazuhitoyokoi** [comment]
@ovflowd @joesepi @anonrig @VoltrexKeyva @ljharb Thank you all. I will do my best!

**Pull request merged**
