### PR TITLE
Travel request for TC39 Plenary

### PR DESCRIPTION
**Pull request by legendecas**
### Info
Request for: TC39 Plenary September 2023, Tokyo, Japan
Dates: 25th – 29th September (The event is on 26th - 28th September)
Traveling from: Shanghai, China (or Hangzhou, China, depending on the flight fees)

I'm working as one of the champions of the TC39 [AsyncContext proposal](https://github.com/tc39/proposal-async-context). It is a language feature similar to Node.js' AsyncLocalStorage. With the proposal made in the ECMAScript, the feature provided by AsyncLocalStorage will be available in browsers and reduce the gap between Node.js and web platforms. 

On 26th-28th September, I'm going to speak at the meeting. It's unfortunate that my employer didn't allocate a budget for international travel. So I'm requesting the travel fund from OpenJS Foundation instead. I'm a collaborator of the Node.js project and participated in it in the past 90 days.

### Estimated Expenses

```
$ 700 Flight (Shanghai/Hangzhou ↔︎ Tokyo)
$ 1280 Hotel
━━━━
$ 1980 Total
```

I will pay all other costs like transportation and food.

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by VoltrexKeyva — APPROVED** [review]

**Review by anonrig — APPROVED** [review]

**Review by ruyadorno — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by bensternthal** [comment]
Note this request is pending Standards Working Group approval.

**Comment by mhdawson** [comment]
To add some additional weight to this request. The TSC discussed this request in the TSC meeting today and we had +1s from 10 of the TSC members present including those who commented through slack earlier endorsing this request as being important to have representation from the Node.js project at the TC39 meeting on this proposal.

**Comment by ljharb** [comment]
The Standards WG approved this request, and thanks to the node TSC for officially supporting it!

**Pull request merged**
