### PR TITLE
Travel request for OpenJS World Europe

### PR DESCRIPTION
**Pull request by bmuenzenmeyer**
# Info

- Request for: Collab Summit and OSSEU 2023 
- Dates: September 16th - September 22nd 
- Travelling from: Minneapolis, Minnesota, United States

# Estimated Expenses

- Flight: ~ $1500 USD (From Minneapolis to Amsterdam to Bilbao, round-trip)
    - Start flight late night of 16th
    - Arrive 17th, afternoon before summit
    - Fly out morning after last day of conference, 22nd.
- Hotel: ~ $1089  Using one of recommended hotels, 5 nights
    - Night before summit
    - Night before day 1 conference
    - Night before day 2 conference
    - Night before day 3 conference
    - Night before return journey home (this is my first international conference travel. I'd imagine a good nights sleep after the conf would be nice...but I understand it's an expense. Feedback welcome)
- Registration:  $275 USD
- Transportation: ~ 0 USD
- Total: ~$2864 USD 

The member will pay all other costs like transportation and food.

@openjs-foundation/cpc

### CODE REVIEW

**Review by ovflowd — APPROVED** [review]
It will be fantastic to have you there!

**Comment by ovflowd** [comment]
For other CPC members, @bmuenzenmeyer has been an

- Issue Triagger for a long time on the Node.js project
- Part of the Website team and doing some awesome work
- Helping with organising some volunteering stuff for the next's Grace Hopper Event
- Hosting a Session on Collab Summit

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by ljharb — APPROVED** [review]

**Comment by ovflowd** [comment]
cc @openjs-foundation/cpc as we need only one more approval here 🙃

**Review by tobie — APPROVED** [review]

**Pull request merged**
