### PR TITLE
Travel request for OpenJS World North America

### PR DESCRIPTION
**Pull request by nebrius**
Hi @openjs-foundation/cpc, I'm a last minute speaking invite for OpenJS World North America in Vancouver, CA on May 10th through 12th. I unfortunately don't have funds to cover travel, and was instructed to submit a request for funds here. My talk will be titled "To Rewrite, or Not to Rewrite, That Is the Question."

I'm requesting hotel and airfare, which is $1503.58 USD as of this writing based on current costs and exchange rates. Let me know if you need to know anything more!

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Review by joesepi — APPROVED** [review]
Yay 🎉

**Comment by nebrius** [comment]
Thanks everyone for the approvals. It seems I need one more person to approve, right? Can I get someone else to approve so I can book before prices go up?

**Review by TheLarkInn — APPROVED** [review]
🚢

**Review by christian-bromann — APPROVED** [review]

**Review by bnb — APPROVED** [review]

**Comment by bnb** [comment]
@nebrius just wanted to make sure you know this is a reimbursement and not up-front funds, right?

**Comment by nebrius** [comment]
Thanks everyone!

> @nebrius just wanted to make sure you know this is a reimbursement and not up-front funds, right?

Yep, I just want to make sure that my funding is confirmed before I book ("don't count your chickens till they hatch" kind of a thing)

**Pull request merged**
