### PR TITLE
Travel Expenses for OpenJS World, Chris Gervang

### PR DESCRIPTION
**Pull request by chrisgervang**
Hello there, I'm a speaker at OpenJS World North America in Vancouver, CA on 12th. I unfortunately don't have funds to cover travel. I'd like to submit expenses for my flight from SFO, and an Airbnb. I've estimated the stipend amount to be $1,942.70. I plan to cover all food/transportation.

cc @openjs-foundation/cpc

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Review by ovflowd — CHANGES_REQUESTED** [review]
Sorry, but this fund is intended only for Collaborators of OpenJS member-projects. Not for speakers at OSSNA. You should have requested travel funds with the LF Events team.

Also, we do not support submitting travel expense requests after the event has started/finished.

**Comment by ovflowd** [comment]
To double-check, I see you're contributing to VisGL. @ljharb, since you approved their PR, are they contributing to OpenVisualization projects for more than 3 months?

I still don't think we can go over the rule of expenses being submitted before the event. But I'm open to suggestions, @openjs-foundation/cpc

**Comment by ovflowd** [comment]
Thank you for filling me in, Jordan! I'd be more than happy to approve the costs that fulfil the requirements.

Let's hear what the rest of the CPC has to say. I'm not sure exceptions are something we should do, I rather that we make amends to the current rules of fund requests allowing the CPC to approve extraordinarily cases.

**Comment by chrisgervang** [comment]
Hi there, I wasn't sure how much context to provide - apologies! I've been an active contributor to vis.gl and kepler.gl since 2017, am on the vis.gl [technical steering committee](https://github.com/visgl/tsc), was previously on the board of Urban Computing Foundation which [we merged into OpenJS last year](https://openjsf.org/blog/2022/06/07/openjs-world-2022-openjs-foundation-welcomes-urban-computing-foundation-vis-gl-and-kepler-gl/), and run many of the Open Visualization bi-weekly community meetings. Robin Ginn and Kylie Wagar-Dirks suggested I use the community fund to attend the OSSNA since my company wasn't able to sponsor my expenses.

I'm sorry for not submitting the expenses earlier. I didn't get approval from my company to give the talk until the week of the event, and so I didn't feel comfortable asking for funds earlier. I will submit for pre-approval earlier next time now that I understand the policy. I'd really appreciate being able to cover some of the expenses with this fund, but of course, will accept and understand CPC's decision.

**Comment by ovflowd** [comment]
@chrisgervang I would always recommend giving a read to the community fund policies beforehands. I understand you didn't know better, but you could have simply reached out to the CPC beforehands to clear any questions.

Note that I would 100% have recommended you to have applied to the fund even if you were still waiting for your company, reason being that even if it gets accepted it doesn't mean you need to use it. Usually we request the fund months prior an event just for a pre-approval. The PR getting merged is not an indication of you actually using the funds.

Now, I know this is a tricky situation, hence I feel we (the CPC) either make an amendment to the current bylaw/policies of the community fund to suit cases like yours or we simply approve this one as an one-timer exception.

Either way I'm fine and more than happy to support you here!

We had a similar case for a non-contributor where the CPC approved for a casual Node.js contributor and speaker at the Collab Summit. (But the Collab Summit is under the OpenJS Foundation hence a different case).

Also keep in mind this is just my interpretation of the bylaws 🙈

Hopefully we get you covered!!

**Comment by ljharb** [comment]
VisGL and OpenJS World are both under the OpenJS Foundation as well, just as much as the collab summit is?

**Comment by ovflowd** [comment]
My understanding is that speaker funds for OpenJS World goes under the Open Source Summit Travel Fund. But again, my understanding. I might be completely at wrong here!

My only concern here is the submit timeline, as it sounds like a hard blocker. Hence wondering if we can go around it.

**Comment by chrisgervang** [comment]
I should have reached out to someone ahead of time. Thank you for your support. The travel-fund README mention this about submission timelines: 

> Requests must be made prior to the start of travel

It also highly recommends I submit way in advance, and I didn't do that. I submitted the PR prior to my flight in this case.

**Review by mcollina — APPROVED** [review]
This is technically outside our policy, as funds should be asked before the event. However, it is the intention of the fund to cover for these kind of issues. So I'm overall LGTM.

I might have missed you, but it seems you didn't attend collab summit, while you were in Vancouver. This leaves me a bit puzzled. It would have been great to have an overview of the new projects.

**Review by tobie — APPROVED** [review]

**Comment by ovflowd** [comment]
Oh hey, @chrisgervang I also just noticed (after re-reading my initial comment) that my tone sounded harsh and non-welcoming 😅, I bet that for you, receiving this sort of message must definitely sound mesmerising.

My autistic brain sometimes doesn't even realise the tone of the messages I write.

I just wanted to ensure that my intent was to abide by current policies, and I was lacking context. I apologise for that 🙇, those are not the standards I want to live by.

I do believe as mentioned before, that we might need to make amends to our current policies to make the whole process more friendlier and inclusive for cases such as yours.

Anyhow, I see we're getting all the needed approvals here, so excited things will work out ✨

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by ljharb** [comment]
It's been more than 72 hours and has > 4 approvals and no blocks, so I'll land this.

**Comment by ljharb** [comment]
@chrisgervang ah, looks like you unchecked "allow edits"; would you mind checking that?

**Review by joesepi — APPROVED** [review]

**Comment by chrisgervang** [comment]
@ljharb, should be checked now. @ovflowd No worries! I know everyone here has the best intentions. Thanks for your help everyone, I'll reach out if I have questions on the following steps.

**Comment by ovflowd** [comment]
We can merge this, right?

**Comment by ljharb** [comment]
whoops yes, will do that shortly.

**Pull request merged**
