### PR TITLE
Add Rafael Silva for travel funding

### PR DESCRIPTION
**Pull request by RafaelGSS**
# Info

Request for: Collab Summit, OSSEU 2023 and OSSF EU 2023
Dates: September 17th - September 22nd 
Traveling from: GRU, Brazil

## Estimated Expenses

Flight: 0 (Nearform will pay for the airfare costs)
Hotel: $1.125,66 USD
Total: $1.125,66 USD

@openjs-foundation/cpc

### CODE REVIEW

**Comment by PaulaPaul** [comment]
@RafaelGSS is speaking (three times!) at the conference -  NearForm is also sending three additional people to the conference (two Node.js core team collaborators) and covering their full costs; since he is speaking they would like to request that his hotel costs are covered. He submitted a request for travel funding to LF, and it was denied.

**Review by mcollina — APPROVED** [review]
lgtm

**Review by ovflowd — APPROVED** [review]
Weird to see LF denied his sponsor request. Well, approved :)

More than happy to see you here with us, Rafael.

**Comment by ovflowd** [comment]
cc @openjs-foundation/cpc for approvals as he's a speaker.

**Review by anonrig — APPROVED** [review]

**Comment by ovflowd** [comment]
@RafaelGSS can you rebase this?

**Review by VoltrexKeyva — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Pull request merged**
