### PR TITLE
Travel Fund request

### PR DESCRIPTION
**Pull request by bnoordhuis**
Hotel + travel costs (Groningen, NL - Bilbao, ES) for the summit in September.

The EUR 1,000 is a conservative guess. In practice it's probably lower.

### CODE REVIEW

**Review by ovflowd — APPROVED** [review]
Huh! I guess we can probably (if you're interested) talk about the 5XX issues and Node.js infra at the Summit, better than in issues :)

**Comment by bnoordhuis** [comment]
I would hope they're fixed by then but sure. :)

**Comment by ovflowd** [comment]
> I would hope they're fixed by then but sure. :)

Same (definitely hopeful of that being fixed by then lol) (sorry for the off-topic heh)

**Review by joesepi — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by ovflowd** [comment]
This got enough approvals and can get merged.

**Pull request merged**
